# plataforma con la cual se utilizara fastlane
default_platform(:android)

platform :android do

# descripción de la lane que se realizara
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: 'clean bundle')
    upload_to_play_store
  end
end
